# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
os:
- linux
#- osx

language: R
sudo: false
cache: packages

addons:
 apt:
   update: true
   packages:
     - libmagick++-dev # imageMagick for linux

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'devtools::install()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
