# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
os:
- linux
- osx

r:
- release
- oldrelease
- devel

sudo: false
cache: packages

addons:
 apt:
   packages:
     - libmagick++-dev # imageMagick for linux
